services:
  - type: web
    name: eduschedule-backend
    runtime: docker
    plan: free
    region: frankfurt
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: APP_FRONTEND_URL
        sync: false
      - key: N8N_WEBHOOK_URL
        sync: false
      - key: N8N_EMAIL_TRIGGER_URL
        sync: false
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx400m
